name: Manual Jar Compilation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'v1.218.0' # Force checks out a fully verified release tag
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Plugin Jar
        run: |
          chmod +x gradlew
          ./gradlew shadowJar --no-daemon -x test

      - name: Upload Finished Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oraxen-Jar
          path: '**/build/libs/*shadow.jar'
