name: Manual Jar Compilation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Build Directories
        run: mkdir -p build/libs

      - name: Fetch Official Stable Release Jar
        run: |
          curl -L -o build/libs/Oraxen.jar https://github.com

      - name: Upload Finished Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oraxen-Jar
          path: build/libs/Oraxen.jar
